
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 30 17:04:57 BRST 2017
//----------------------------------------------------

package principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BGN = 4;
  public static final int ADDOP = 12;
  public static final int READ = 17;
  public static final int ELSE = 21;
  public static final int RELOP = 11;
  public static final int A_PAREM = 9;
  public static final int THEN = 20;
  public static final int WHILE = 16;
  public static final int CONSTANT = 23;
  public static final int IDENTIFIER = 25;
  public static final int END = 5;
  public static final int IF = 19;
  public static final int LITERAL = 13;
  public static final int WRITE = 18;
  public static final int MULOP = 14;
  public static final int DO = 15;
  public static final int NUMBER = 24;
  public static final int EOF = 0;
  public static final int VIRG = 7;
  public static final int PRG = 2;
  public static final int error = 1;
  public static final int ATR = 22;
  public static final int F_PAREM = 10;
  public static final int DCL = 3;
  public static final int INTEGER = 8;
  public static final int P_VIRG = 6;
}

